name: CMake

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build-firmware:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest
    name: build-frmware

    steps:
    - uses: actions/checkout@v4

    - name: Install libs
      # Some projects don't allow in-source building, so create a separate build directory
      # We'll use this as our working directory for all subsequent commands
      run: sudo apt-get install -y gcc-arm-none-eabi

    - name: Build firmware
      shell: bash
      run: make -C src/firmware

    - uses: actions/upload-artifact@v4
      with:
        name: firmware
        path: ./src/firmware/SDDC_FX3.img

  build-on-windows:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: windows-latest
    needs: build-firmware

    steps:
    - uses: actions/checkout@v4

    - name: Install vcpkg dependencies
      run: cd c:\vcpkg ; git pull ; vcpkg install soapysdr:x64-windows

    - name: Create Build Environment
      # Some projects don't allow in-source building, so create a separate build directory
      # We'll use this as our working directory for all subsequent commands
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      # Use a bash shell so we can use the same syntax for environment variable
      # access regardless of the host operating system
      shell: bash
      working-directory: ${{runner.workspace}}/build
      # Note the current convention is to use the -S and -B options here to specify source
      # and build directories, but this is only available with CMake 3.13 and higher.
      # The CMake binaries on the Github Actions machines are (as of this writing) 3.12
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -G "Visual Studio 17 2022" -A Win32

    - uses: actions/download-artifact@v4
      with:
        name: firmware

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      # Execute the build.  You can specify a specific target with "--target <NAME>"
      run: cmake --build . --config $BUILD_TYPE

    - name: Create Build64 Environment
      run: cmake -E make_directory ${{runner.workspace}}/build64

    - name: Configure CMake64
      shell: bash
      working-directory: ${{runner.workspace}}/build64
      run: cmake $GITHUB_WORKSPACE "-DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake" -DCMAKE_BUILD_TYPE=$BUILD_TYPE -G "Visual Studio 17 2022"

    - name: Build
      working-directory: ${{runner.workspace}}/build64
      shell: bash
      # Execute the build.  You can specify a specific target with "--target <NAME>"
      run: cmake --build . --config $BUILD_TYPE

    - name: Install FFTW3
      working-directory: ${{runner.workspace}}/build
      shell: powershell
      # Execute the build.  You can specify a specific target with "--target <NAME>"
      run: Invoke-WebRequest -Uri "ftp://ftp.fftw.org/pub/fftw/fftw-3.3.5-dll32.zip" -OutFile fftw-3.3.5-dll32.zip

    - name: Unzip FFTW3
      working-directory: ${{runner.workspace}}/build
      shell: powershell
      # Execute the build.  You can specify a specific target with "--target <NAME>"
      run: Expand-Archive -Path .\fftw-3.3.5-dll32.zip -DestinationPath 

    - name: Run CPack for ExtIO
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: |
        # Create a ZIP-only package for the extio component. Set a normalized
        # package base name: <component>-<os>-<arch>
        echo "Running cpack for extio"
        COMPONENT=extio
        OS="windows"
        ARCH=Win32
        export CPACK_PACKAGE_FILE_NAME="${COMPONENT}-${OS}-${ARCH}"
        CPACK_GENERATOR="ZIP" cpack --config CPackConfig.cmake --component "${COMPONENT}"

    - name: Upload ExtIO package
      uses: actions/upload-artifact@v4
      with:
        name: windows-packages
        path: ${{runner.workspace}}/build/*.zip

  build-on-linux:
    runs-on: 
        runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: x86_64
          - os: ubuntu-22.04-arm
            arch: arm64

    steps:
    - uses: actions/checkout@v4

    - name: Install libs
      # Some projects don't allow in-source building, so create a separate build directory
      # We'll use this as our working directory for all subsequent commands
      run: sudo apt-get install -y libfftw3-dev libusb-1.0-0-dev gcc-arm-none-eabi libsoapysdr-dev

    - name: Create Build Environment
      # Some projects don't allow in-source building, so create a separate build directory
      # We'll use this as our working directory for all subsequent commands
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      # Use a bash shell so we can use the same syntax for environment variable
      # access regardless of the host operating system
      shell: bash
      working-directory: ${{runner.workspace}}/build
      # Note the current convention is to use the -S and -B options here to specify source
      # and build directories, but this is only available with CMake 3.13 and higher.
      # The CMake binaries on the Github Actions machines are (as of this writing) 3.12
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      # Execute the build.  You can specify a specific target with "--target <NAME>"
      run: cmake --build . --config $BUILD_TYPE

    - name: Test
      working-directory: ${{runner.workspace}}/build
      shell: bash
      # Execute tests defined by the CMake configuration.
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest -C $BUILD_TYPE

    - name: Run CPack
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: |
        OS="linux"
        ARCH=${{ matrix.arch }}
        CPACK_PACKAGE_FILE_NAME="libsddc-${OS}-${ARCH}" CPACK_GENERATOR="TGZ;ZIP" cpack --config CPackConfig.cmake --component libsddc
        CPACK_PACKAGE_FILE_NAME="soapy-${OS}-${ARCH}" CPACK_GENERATOR="TGZ;ZIP" cpack --config CPackConfig.cmake --component soapy

    - uses: actions/upload-artifact@v4
      with:
        name: linux-packages
        path: |
          ${{runner.workspace}}/build/libsddc-*
          ${{runner.workspace}}/build/soapy-*

  build-on-macos:
    name: build-on-macos
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-15-intel
            arch: x86_64
          - os: macos-latest
            arch: arm64
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          brew update
          brew install soapysdr
          brew install fftw

      - name: Configure and Install SoapySDR Module
        shell: bash
        working-directory: ${{ runner.workspace }}
        run: |
          set -euo pipefail
          build_dir="${{ runner.workspace }}/build"
          mkdir -p "${build_dir}"
          cd "${build_dir}"
          cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_OSX_ARCHITECTURES=${{ matrix.arch }}
          cmake --build . --config $BUILD_TYPE

      - name: Run CPack
        shell: bash
        working-directory: ${{ runner.workspace }}/build
        run: |
          OS="osx"
          ARCH=${{ matrix.arch }}
          CPACK_PACKAGE_FILE_NAME="libsddc-${OS}-${ARCH}" CPACK_GENERATOR="TGZ;ZIP" cpack --config CPackConfig.cmake --component libsddc
          CPACK_PACKAGE_FILE_NAME="soapy-${OS}-${ARCH}" CPACK_GENERATOR="TGZ;ZIP" cpack --config CPackConfig.cmake --component soapy

      - name: Upload package (from build)
        uses: actions/upload-artifact@v4
        with:
          name: osx-${{ matrix.arch }}-packages
          path: |
            ${{runner.workspace}}/build/libsddc-*
            ${{runner.workspace}}/build/soapy-*

            ${{ runner.workspace }}/build-${{ matrix.arch }}/*.tar.gz
            ${{ runner.workspace }}/build-${{ matrix.arch }}/*.zip